logging.level.root: error

spring.main.banner-mode: "off"
spring:
  datasource:
    url: jdbc:h2:mem:~/test
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    database-platform: com.luxoft.logeek.config.CustomH2Dialect
